"""add goods table

Revision ID: 261c4909d2d2
Revises: db6f043203a2
Create Date: 2024-06-20 20:37:43.138495

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "261c4909d2d2"
down_revision = "db6f043203a2"
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_goods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True, comment="名称"),
        sa.Column("pic_url", sa.String(length=128), nullable=True, comment="封面图url"),
        sa.Column("description", sa.String(length=255), nullable=True, comment="描述"),
        sa.Column("data", sa.BLOB(), nullable=True, comment="二进制数据"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="商店货物表",
    )
    op.create_index(op.f("ix_sys_goods_id"), "sys_goods", ["id"], unique=False)
    op.create_index(op.f("ix_sys_goods_name"), "sys_goods", ["name"], unique=True)
    op.add_column(
        "sys_inventory",
        sa.Column("user", sa.String(length=32), nullable=True, comment="用户名"),
    )
    op.add_column(
        "sys_inventory",
        sa.Column(
            "become_user", sa.String(length=32), nullable=True, comment="提权用户"
        ),
    )
    op.add_column(
        "sys_inventory",
        sa.Column(
            "become_password", sa.String(length=64), nullable=True, comment="提权密码"
        ),
    )
    op.add_column(
        "sys_inventory",
        sa.Column("port", sa.Integer(), nullable=True, comment="ssh端口"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sys_inventory", "port")
    op.drop_column("sys_inventory", "become_password")
    op.drop_column("sys_inventory", "become_user")
    op.drop_column("sys_inventory", "user")
    op.drop_index(op.f("ix_sys_goods_name"), table_name="sys_goods")
    op.drop_index(op.f("ix_sys_goods_id"), table_name="sys_goods")
    op.drop_table("sys_goods")
    # ### end Alembic commands ###
