"""init project

Revision ID: db6f043203a2
Revises:
Create Date: 2024-06-13 10:43:09.920483

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db6f043203a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_inventory",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("hostname", sa.String(length=32), nullable=True, comment="主机名"),
        sa.Column("password", sa.String(length=64), nullable=True, comment="密码"),
        sa.Column(
            "ipv4_address", sa.String(length=16), nullable=True, comment="ipv4地址"
        ),
        sa.Column(
            "ipv6_address", sa.String(length=64), nullable=True, comment="ipv6地址"
        ),
        sa.Column("vault_id", sa.String(length=32), nullable=True, comment="vault标识"),
        sa.Column("vault", sa.String(length=32), nullable=True, comment="保险库密码"),
        sa.Column("status", sa.SmallInteger(), nullable=True, comment="状态"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="主机清单表",
    )
    op.create_index(
        op.f("ix_sys_inventory_hostname"), "sys_inventory", ["hostname"], unique=True
    )
    op.create_index(op.f("ix_sys_inventory_id"), "sys_inventory", ["id"], unique=False)
    op.create_table(
        "sys_user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True, comment="用户名"),
        sa.Column("password", sa.String(length=64), nullable=True, comment="密码"),
        sa.Column("nickname", sa.String(length=32), nullable=True, comment="昵称"),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("update_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="用户信息表",
    )
    op.create_index(op.f("ix_sys_user_id"), "sys_user", ["id"], unique=False)
    op.create_index(op.f("ix_sys_user_username"), "sys_user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sys_user_username"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_id"), table_name="sys_user")
    op.drop_table("sys_user")
    op.drop_index(op.f("ix_sys_inventory_id"), table_name="sys_inventory")
    op.drop_index(op.f("ix_sys_inventory_hostname"), table_name="sys_inventory")
    op.drop_table("sys_inventory")
    # ### end Alembic commands ###
